const menu = [
  {
    id: 1,
    title: "COSMOPOLITAN",
    category: "Shaken",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `The days of the Cosmo as the bartender’s piñata are over. You may even see crafted spins on this drink, but mostly, there’s indifference. If you need reminding, it’s vodka, triple sec, cranberry, and lime. Despite dropping 14 spots since 2017, the Cosmo has remained relevant, meaning it might be time to give the pink drink a second chance.`,
  },
  {
    id: 2,
    title: "TOM COLLINS",
    category: "Built",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `The original Tom Collins recipe calls for gin, lemon, and soda water; essentially, it’s a spritzy lemonade for grownups. This quintessential gin Highball, however, has fallen five places since the previous year’s list was released.`,
  },
  {
    id: 3,
    title: "AVIATION",
    category: "Shaken",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `After acquainting yourself with Tom Collins, meet an Aviation: Served up in a Martini glass, the gorgeous lavender-colored cocktail is made with Crème de Violette or Creme Yvette, Maraschino liqueur, gin, and lemon juice. The Aviation has had a bumpy flight these past few years, descending 15 spots since last year.`,
  },
  {
    id: 4,
    title: "BRANDY CRUSTA",
    category: "Built",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `The Brandy Crusta is a complex creation inspired by New Orleans cocktail culture. It is a delicate combination of brandy, curaçao, lemon juice, simple syrup, Angostura bitters, and Maraschino liqueur.`,
  },
  {
    id: 5,
    title: "AMERICANO",
    category: "Stirred",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Not to be confused with the espresso drink (in fact, it has nothing to do with coffee at all), this Italian cocktail was created by Gaspare Campari, who served it in his bar Caffè Campari in the 1860s. This Campari, vermouth, and soda water drink is quickly rising in popularity.`,
  },
  {
    id: 6,
    title: "SAZERAC",
    category: "Stirred",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: "DARK ’N’ STORMY",
    category: "Built",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `The Dark ’n’ Stormy contains a mix of Gosling’s rum (and only Gosling’s rum) and ginger beer. Sometimes, simplest is best.`,
  },
  {
    id: 8,
    title: "MOJITO",
    category: "Built",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `The Mojito might be Cuba’s most popular contribution to cocktail culture. The mix of white rum, lime juice, cane sugar, and soda (with muddled mint, please) is fresh and tropical, and it’s a classic that we don’t expect to disappear any time soon.`,
  },
  {
    id: 9,
    title: "MARGARITA",
    category: "Shaken",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `The Margarita, in its tart, tangy simplicity, is probably the most well-known tequila cocktail in the world. It’s also one of the most popular cocktails in America. It keeps its spot as the world’s top tequila-based classic in 2021.`,
  },
];
export default menu;
